[[manager.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm
''', "yank" ]

[[manager.prepend_keymap]]
on = [ "c", "a" ]
run = "plugin compress"
desc = "Compress to archive"

[[manager.prepend_keymap]]
on = "Space"
run = "select --state=none"
desc = "Toggle the current selection state"
