[completion]
[completion.active]
bg = "#424242"
fg = "#a988b0"

[completion.border]
fg = "#99a2d9"

[completion.inactive]
fg = "#ccc6c6"

[[filetype.rules]]
fg = "#70bbcc"
mime = "image/*"

[[filetype.rules]]
fg = "#d9bc8c"
mime = "video/*"

[[filetype.rules]]
fg = "#d9bc8c"
mime = "audio/*"

[[filetype.rules]]
fg = "#a988b0"
mime = "application/zip"

[[filetype.rules]]
fg = "#a988b0"
mime = "application/gzip"

[[filetype.rules]]
fg = "#a988b0"
mime = "application/x-tar"

[[filetype.rules]]
fg = "#a988b0"
mime = "application/x-bzip"

[[filetype.rules]]
fg = "#a988b0"
mime = "application/x-bzip2"

[[filetype.rules]]
fg = "#a988b0"
mime = "application/x-7z-compressed"

[[filetype.rules]]
fg = "#a988b0"
mime = "application/x-rar"

[[filetype.rules]]
fg = "#a988b0"
mime = "application/xz"

[[filetype.rules]]
fg = "#7bcc8f"
mime = "application/doc"

[[filetype.rules]]
fg = "#7bcc8f"
mime = "application/pdf"

[[filetype.rules]]
fg = "#7bcc8f"
mime = "application/rtf"

[[filetype.rules]]
fg = "#7bcc8f"
mime = "application/vnd.*"

[[filetype.rules]]
bold = true
fg = "#99a2d9"
mime = "inode/directory"

[[filetype.rules]]
fg = "#ccc6c6"
mime = "*"

[help]
[help.desc]
fg = "#ccc6c6"

[help.footer]
fg = "#ccc6c6"

[help.hovered]
bg = "#424242"
fg = "#ccc6c6"

[help.on]
fg = "#a988b0"

[help.run]
fg = "#70bbcc"

[input]
[input.border]
fg = "#99a2d9"

[input.selected]
bg = "#424242"

[input.title]
fg = "#ccc6c6"

[input.value]
fg = "#ccc6c6"

[manager]
syntect_theme = "/nix/store/z29n8dss6dn1zcfnj31dwhnw7pmahlkg-untitled/base16-untitled.tmTheme"
[manager.border_style]
fg = "#8c8888"

[manager.cwd]
fg = "#70bbcc"

[manager.find_keyword]
bold = true
fg = "#7bcc8f"

[manager.find_position]
fg = "#ccc6c6"

[manager.hovered]
bg = "#424242"
bold = true
fg = "#ccc6c6"

[manager.marker_copied]
bg = "#d9bc8c"
fg = "#d9bc8c"

[manager.marker_cut]
bg = "#cc7073"
fg = "#cc7073"

[manager.marker_selected]
bg = "#7bcc8f"
fg = "#7bcc8f"

[manager.preview_hovered]
bg = "#424242"
bold = true
fg = "#ccc6c6"

[manager.tab_active]
bg = "#99a2d9"
fg = "#151515"

[manager.tab_inactive]
bg = "#1f1f1f"
fg = "#ccc6c6"

[select]
[select.active]
fg = "#a988b0"

[select.border]
fg = "#99a2d9"

[select.inactive]
fg = "#ccc6c6"

[status]
[status.mode_normal]
bg = "#99a2d9"
bold = true
fg = "#151515"

[status.mode_select]
bg = "#7bcc8f"
bold = true
fg = "#151515"

[status.mode_unset]
bg = "#bbb6b6"
bold = true
fg = "#151515"

[status.permissions_r]
fg = "#d9bc8c"

[status.permissions_s]
fg = "#70bbcc"

[status.permissions_t]
fg = "#99a2d9"

[status.permissions_w]
fg = "#cc7073"

[status.permissions_x]
fg = "#7bcc8f"

[status.progress_error]
bg = "#151515"
fg = "#cc7073"

[status.progress_label]
bg = "#151515"
fg = "#ccc6c6"

[status.progress_normal]
bg = "#151515"
fg = "#ccc6c6"

[status.separator_style]
bg = "#1f1f1f"
fg = "#1f1f1f"

[tasks]
[tasks.border]
fg = "#99a2d9"

[tasks.hovered]
bg = "#424242"
fg = "#ccc6c6"

[tasks.title]
fg = "#ccc6c6"

[which]
[which.cand]
fg = "#70bbcc"

[which.desc]
fg = "#ccc6c6"

[which.mask]
bg = "#333333"

[which.rest]
fg = "#bbb6b6"

[which.separator_style]
fg = "#8c8888"

