file_watch_support = false

# SVELTE --------------------------
[[language]]
name = "svelte"
comment-token = "//"
block-comment-tokens = {start = "<!--", end = "-->"}

# NIX --------------------------
[[language]]
auto-format = true
language-servers = ["nix"]
name = "nix"

[language.formatter]
command = "nixfmt"

[language-server.nix]
command = "nil"


# RUST --------------------------
[[language]]
name = "rust"

[language.auto-pairs]
"\"" = "\""
"(" = ")"
"<" = ">"
"[" = "]"
"`" = "`"
"{" = "}"

[language-server.rust-analyzer.config]
check.command = "clippy"


# PYTHON --------------------------
[[language]]
name = "python"
auto-format = true
language-servers = ["ruff", "pylsp"]

[language.formatter]
args = ["--line-length", "88", "--quiet", "-"]
command = "black"


# JSON --------------------------
[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome"]

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = ["tsconfig.json", "tsconfig.*.json"]
url = "https://json.schemastore.org/tsconfig.json"

[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = [ "package.json" ]
url = "https://json.schemastore.org/package.json"

