file_watch_support = true

# SVELTE --------------------------
[[language]]
name = "svelte"
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }
block-comment-tokens = {start = "<!--", end = "-->"}
language-servers = [ "svelteserver", "tailwindcss" ]
formatter = { command = "prettier", args = ["--parser", "svelte"] }

[language-server.svelteserver.config.configuration.typescript]
inlayHints.parameterTypes.enabled = false
inlayHints.variableTypes.enabled = false
inlayHints.propertyDeclarationTypes.enabled = false
inlayHints.functionLikeReturnTypes.enabled = false
inlayHints.enumMemberValues.enabled = false
inlayHints.parameterNames.enabled = false


[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

# ARDUINO --------------------------

[[language]]
name = "cpp"
formatter.command = "clang-format"

# NIX --------------------------
[[language]]
language-servers = ["nix"]
name = "nix"

[language.formatter]
command = "alejandra"

[language-server.nix]
command = "nixd"

# TS -----------------------
[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
roots = ["package-lock.json", "tsconfig.json", ".prettierrc.json"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

# RUST --------------------------
[[language]]
name = "rust"

[language.auto-pairs]
"\"" = "\""
"(" = ")"
"<" = ">"
"[" = "]"
"`" = "`"
"{" = "}"

[language-server.rust-analyzer.config]
cache.warmup = true
cachePriming.numThreads = 12
numThreads = 12
lru.capacity = 512
cargo.buildScripts.enable = false
cargo.noDeps = true

check.command = "clippy"
check.invocationStrategy = "once"
check.allTargets = false
checkOnSave = true

references.excludeTests = true
references.excludeImports = true

diagnostics.disabled = ["proc-macro-disabled"]
diagnostics.styleLints.enable = true

procMacro.ignored.tauri_macros = [ "command", "generate_handler" ]
procMacro.ignored.async_trait = [ "async-trait"]
procMacro.ignored.tokio_macros = [ "main" ]
procMacro.ignored.embassy_executor_macros = [ "main" ]

completion.autoAwait.enable = false
completion.autoIter.enable = false
completion.autoimport.enable = true
completion.hideDeprecated = true
completion.postfix.enable = false
completion.autoself.enable = false

inlayHints.maxLength = 15
inlayHints.renderColons = false
inlayHints.implicitDrops.enable = false
inlayHints.implicitSizedBoundHints.enable = true
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.lifetimeElisionHints.useParameterNames = true
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.closureCaptureHints.enable = true
inlayHints.genericParameterHints.lifetime.enable = true
inlayHints.genericParameterHints.type.enable = true
inlayHints.expressionAdjustmentHints.mode = "prefer_prefix" # prefix | postfix | prefer _
inlayHints.expressionAdjustmentHints.enable = "reborrow" # always | never | reborrow
inlayHints.expressionAdjustmentHints.hideOutsideUnsafe = false
inlayHints.closingBraceHints.minLines = 8
inlayHints.parameterHints.enable = false
inlayHints.typeHints.hideClosureInitialization = true
inlayHints.typeHints.hideNamedConstructor = true
inlayHints.rangeExclusiveHints.enable = true
inlayHints.discriminantHints.enable = "fieldless"

lens.enable = false
assist.expressionFillDefault = "todo"
assist.termSearch.borrowcheck = false
assist.termSearch.fuel = 1000
files.excludeDirs = [ ".git", "target" ]

# PYTHON --------------------------
[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]

[language.formatter]
args = ["--line-length", "88", "--quiet", "-"]
command = "black"

# HTML ------------------------------------
[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = [ "superhtml", "tailwindcss" ]

# JSON --------------------------
[[language]]
name = "json"
language-servers = [ "json", "biome"]

[language-server.json]
command = "vscode-json-language-server"
except-features = [ "format" ]
args = ["--stdio"]

[language-server.json.config.json]
validate = { enable = true }
format = { enable = true }
schemas = [{ fileMatch = ["tsconfig.json", "tsconfig.*.json"], url = "https://json.schemastore.org/tsconfig.json" }, { fileMatch = [ "package.json" ], url = "https://json.schemastore.org/package.json" }]

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]
