{
  lib,
  config,
  ...
}: let
  inherit (lib) mkEnableOption mkIf;
  cfg = config.module.bat;
in {
  options = {
    module.bat = {
      enable = mkEnableOption "enable bat";
    };
  };
  config = mkIf cfg.enable {
    programs.bat = {
      enable = true;
      config = {
        theme = "theme";
        style = "numbers,changes";
      };
    };
    home.sessionVariables.BAT_THEME="theme";
    xdg.configFile."bat/themes/theme.tmTheme".text = let
      helix = config.programs.helix.themes.paradise;
    in ''
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
          <dict>
              <key>author</key>
              <string>Template: Chris Kempson, Scheme: Mitchell Kember</string>
              <key>name</key>
              <string>Base16</string>
              <key>colorSpaceName</key>
              <string>sRGB</string>
              <key>settings</key>
              <array>
                  <dict>
                      <key>settings</key>
                      <dict>
                          <key>background</key>
                          <string>#00000000</string>
                          <key>caret</key>
                          <string>#07000000</string>
                          <key>foreground</key>
                          <string>#07000000</string>
                          <key>invisibles</key>
                          <string>#08000000</string>
                          <key>lineHighlight</key>
                          <string>#08000000</string>
                          <key>selection</key>
                          <string>#0b000000</string>
                          <key>gutter</key>
                          <string>#0a000000</string>
                          <key>gutterForeground</key>
                          <string>#08000000</string>
                      </dict>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>Parentheses, Brackets, Braces</string>
                    <key>scope</key>
                    <string>punctuation</string>
                    <key>settings</key>
                    <dict>
                      <key>foreground</key>
                      <string>${helix."punctuation.bracket"}</string>
                    </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Text</string>
                      <key>scope</key>
                      <string>variable.parameter.function</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix."variable.parameter"}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Comments</string>
                      <key>scope</key>
                      <string>comment, punctuation.definition.comment</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.comment}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Keywords</string>
                      <key>scope</key>
                      <string>keyword</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.keyword}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Variables</string>
                      <key>scope</key>
                      <string>variable, constant.other</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.variable}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Functions</string>
                      <key>scope</key>
                      <string>entity.name.function, meta.require, support.function.any-method</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.function}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Labels</string>
                      <key>scope</key>
                      <string>entity.name.label</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.label}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Operator</string>
                      <key>scope</key>
                      <string>keyword.operator.comparison</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.operator}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Classes</string>
                      <key>scope</key>
                      <string>support.class, entity.name.class, entity.name.type.class</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.type}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Classes</string>
                      <key>scope</key>
                      <string>keyword, meta.class, meta.enum, entity.name.constant, variable.other.constant, variable.type, support.class, support.type, variable.other.class</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.keyword}</string>
                      </dict>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>Rust enum member</string>
                    <key>scope</key>
                    <string>meta.enum.rust storage.type.source.rust</string>
                    <key>settings</key>
                    <dict>
                      <key>foreground</key>
                      <string>${helix.keyword}</string>
                    </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Storage</string>
                      <key>scope</key>
                      <string>storage</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.keyword}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Strings, Inherited Class</string>
                      <key>scope</key>
                      <string>string, punctuation.definition.string, constant.other.placeholder</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.string}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Integers</string>
                      <key>scope</key>
                      <string>constant.numeric</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix."constant.numeric"}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Boolean</string>
                      <key>scope</key>
                      <string>none</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix."constant.builtin"}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Constants</string>
                      <key>scope</key>
                      <string>constant</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix."constant.builtin"}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Tags</string>
                      <key>scope</key>
                      <string>entity.name.tag, entity.name</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.tag}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Attributes</string>
                      <key>scope</key>
                      <string>entity.other.attribute-name</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix."variable.other.member"}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Headings</string>
                      <key>scope</key>
                      <string>markup.heading punctuation.definition.heading, entity.name.section, markup.heading - text.html.markdown</string>
                      <key>settings</key>
                      <dict>
                          <key>fontStyle</key>
                          <string></string>
                          <key>foreground</key>
                          <string>${helix.punctuation}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Bold</string>
                      <key>scope</key>
                      <string>markup.bold, punctuation.definition.bold</string>
                      <key>settings</key>
                      <dict>
                          <key>fontStyle</key>
                          <string>bold</string>
                          <key>foreground</key>
                          <string>#03000000</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Italic</string>
                      <key>scope</key>
                      <string>markup.italic, punctuation.definition.italic</string>
                      <key>settings</key>
                      <dict>
                          <key>fontStyle</key>
                          <string>italic</string>
                          <key>foreground</key>
                          <string>#05000000</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Code</string>
                      <key>scope</key>
                      <string>markup.raw.inline</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>#02000000</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Link Text</string>
                      <key>scope</key>
                      <string>string.other.link, punctuation.definition.string.end.markdown, punctuation.definition.string.begin.markdown</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>#01000000</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Link Url</string>
                      <key>scope</key>
                      <string>meta.link</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>#09000000</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Quotes</string>
                      <key>scope</key>
                      <string>markup.quote string.quoted</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix.string}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Separator</string>
                      <key>scope</key>
                      <string>meta.separator</string>
                      <key>settings</key>
                      <dict>
                          <key>background</key>
                          <string>#0b000000</string>
                          <key>foreground</key>
                          <string>#07000000</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Inserted</string>
                      <key>scope</key>
                      <string>markup.inserted</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>#02000000</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Deleted</string>
                      <key>scope</key>
                      <string>markup.deleted</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>#01000000</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Changed</string>
                      <key>scope</key>
                      <string>markup.changed</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>#05000000</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Regular Expressions</string>
                      <key>scope</key>
                      <string>string.regexp</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix."string.regexp"}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Escape Characters</string>
                      <key>scope</key>
                      <string>constant.character.escape</string>
                      <key>settings</key>
                      <dict>
                          <key>foreground</key>
                          <string>${helix."constant.character.escape"}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Illegal</string>
                      <key>scope</key>
                      <string>invalid.illegal</string>
                      <key>settings</key>
                      <dict>
                          <key>background</key>
                          <string>${helix.error}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Broken</string>
                      <key>scope</key>
                      <string>invalid.broken</string>
                      <key>settings</key>
                      <dict>
                          <key>background</key>
                          <string>${helix.error}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Deprecated</string>
                      <key>scope</key>
                      <string>invalid.deprecated</string>
                      <key>settings</key>
                      <dict>
                          <key>background</key>
                          <string>${helix.warning}</string>
                      </dict>
                  </dict>
                  <dict>
                      <key>name</key>
                      <string>Unimplemented</string>
                      <key>scope</key>
                      <string>invalid.unimplemented</string>
                      <key>settings</key>
                      <dict>
                          <key>background</key>
                          <string>${helix.warning}</string>
                      </dict>
                  </dict>
              </array>
              <key>uuid</key>
              <string>uuid</string>
          </dict>
      </plist>
    '';
  };
}
